name: CI

on: [push]

jobs:
  ci:
    name: CI
    uses: equalogic/actions/.github/workflows/node-ci.yml@master
    with:
      build-check-command: |
        if [ ! -f ./dist/index.js ]; then
          echo "Something went wrong: no ./dist/index.js file was built!"
          exit 1
        else
          echo "Build appears to be successful: ./dist/index.js was created"
        fi
    secrets: inherit

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Setup Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Restore node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules.tar.zstd
      - name: Unarchive node_modules
        run: tar --use-compress-program "zstd -d --long=31" -xf node_modules.tar.zstd
      # Tests
      - name: Run project tests
        run: npm run test:ci
        env:
          CI: true
