name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  npm:
    name: NPM
    uses: equalogic/actions/.github/workflows/npm-publish.yml@master
    with:
      build-check-command: |
        if [ ! -f ./dist/index.js ]; then
          echo "Something went wrong: no ./dist/index.js file was built!"
          exit 1
        else
          echo "Build appears to be successful: ./dist/index.js was created"
        fi
      dist-path: dist/
      prepare-dist-command: cp package.json README* dist/
    secrets: inherit
